# This file was generated by GoReleaser. DO NOT EDIT.
class WpeCli < Formula
  desc "WP Engine DevKit Command Line Interface"
  homepage "https://wpengine.com"
  version "0.19.1"
  bottle :unneeded

  if OS.mac?
    url "https://s3-us-east-2.amazonaws.com/wpeclibinaries/wpe-cli/v0.19.1/wpe-cli_0.19.1_darwin_amd64.tar.gz"
    sha256 "9073755e327f9a29dee586ac4ba85324bddda9305fca02ebf0df0793682a172e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://s3-us-east-2.amazonaws.com/wpeclibinaries/wpe-cli/v0.19.1/wpe-cli_0.19.1_linux_amd64.tar.gz"
      sha256 "cb1619991d504c649b4aacac07a6811a99e46f949e6917a08bb28b8bce367fef"
    end
  end
  
  devel do
    url "https://s3-us-east-2.amazonaws.com/wpeclinightly/wpe-cli/nightly/wpe-cli_nightly_darwin_amd64.tar.gz"
  end

  def install
    bin.install "wpe"
  end

  test do
    system "#{bin}/wpe version"
  end
end
