# This file was generated by GoReleaser. DO NOT EDIT.
class WpeCli < Formula
  desc "WP Engine DevKit Command Line Interface"
  homepage "https://wpengine.com"
  version "0.14.9"
  bottle :unneeded

  if OS.mac?
    url "https://s3-us-east-2.amazonaws.com/wpeclibinaries/wpe-cli/v0.14.9/wpe-cli_0.14.9_darwin_amd64.tar.gz"
    sha256 "9abae0659c14c8d2ed10d51655d1a948a1171badcb920d3ce744237440d93ffd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://s3-us-east-2.amazonaws.com/wpeclibinaries/wpe-cli/v0.14.9/wpe-cli_0.14.9_linux_amd64.tar.gz"
      sha256 "dfea1bc9c5b51234d3f8b21f19da28f6cffb1a944fa84a7174bb8db2068ba52c"
    end
  end
  
  devel do
    url "https://s3-us-east-2.amazonaws.com/wpeclinightly/wpe-cli/nightly/wpe-cli_nightly_darwin_amd64.tar.gz"
  end

  def install
    bin.install "wpe"
  end

  test do
    system "#{bin}/wpe version"
  end
end
